### ISSUE TITLE
Setup/Config Issue

### ISSUE THREAD

**Issue by tomatobrown** [s1ider/sublime-behave-step-finder#1]
Thanks Denis, this is going to be great when I get it working.  Only problem is that I can't get the package to work.  I've setup my framework exactly the same as the behave tutorial with a "feature" folder as the parent of the "steps" folder.  I've named the steps folder "[FileName]_steps.py" to match the config file.  However, when I run Find Behave Step or Match Behave Step nothing seem to happen.  Any idea on what I might be missing?  Also, on Sublime 3 I can't find the location of the config file.

**Comment by s1ider** [comment]
I assumed double quotes in step definitions, that's why plugin didn't work for you for behave tutorial.
Commit b7c2044ed0f4c6b7f85f78bb62268a34cf9e50e7 fixes this.
Upgrade BehaveStepFinder plugin or use double quotes in step definitions instead of single quotes :).

**Comment by tomatobrown** [comment]
Fixed, thanks
